name: JogjaIstimewa
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.5.0
  rounded_loading_button: ^2.1.0
  responsive_sizer: ^3.1.1
  smooth_page_indicator: ^1.1.0
  page_transition: ^2.0.9
  flutter_chat_ui: ^1.6.9
  animated_bottom_navigation_bar: ^1.2.0
  video_player: ^2.6.0
  cached_video_player: ^2.0.4
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  animate_do: ^3.0.2
  cached_network_image: ^3.3.1
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.3.0

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/jogja-istimewa.png
    - images/google.png
    - images/apple.png
    - images/onboarding1.png
    - images/onboarding2.png
    - images/onboarding3.png
    - images/p.png
    - images/DIY.png
    - images/facebook.png
    - lib/icons/
